stages:
  - preparation
image: nguyentruongson93/php:7.4
composer:
  stage: preparation
  before_script:
    - docker-php-ext-configure gd --enable-gd --with-jpeg
    - docker-php-ext-install pdo pdo_mysql gd exif
    - docker-php-ext-enable pdo_mysql gd imagick exif
  script:
    - composer install
    - ./vendor/bin/phpcs
