stages:
  - phpcs
  - unitest
  - deloy
cache:
  paths:
    - vendor/
    - node_modules/
.init_ssh: &init_ssh |
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

image: dungnt1312/php7.4
phpcs:
  stage: phpcs
  script:
    - composer install
    - ./vendor/bin/phpcs
unitest:
  stage: unitest
  script:
    - php artisan test
staging:
  stage: deploy
  script:
    - *init_ssh
    - ./vendor/bin/envoy run deploy --server=dev
  when: manual
  only:
    - dev
