stages:
  - preparation
image: php:7.4
composer:
  stage: preparation
  script:
    - apt-get update -yqq
    - apt-get install git zip zlib1g-dev libzip-dev libxml2-dev libpng-dev libjpeg-dev libghc-curl-dev libldb-dev libldap2-dev libpq-dev -yqq
    - ln -s /usr/lib/x86_64-linux-gnu/libldap.so /usr/lib/libldap.so && ln -s /usr/lib/x86_64-linux-gnu/liblber.so /usr/lib/liblber.so
    - docker-php-ext-configure gd --enable-gd --with-jpeg
    - docker-php-ext-install pdo pdo_mysql gd exif ldap
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=2.0.9
    - composer install
    - ./vendor/bin/phpcs
