<?php

namespace App\Admin\Controllers;

use App\Models\Category;
use Encore\Admin\Controllers\AdminController;
use Encore\Admin\Form;
use Encore\Admin\Grid;
use Encore\Admin\Layout\Content;
use Encore\Admin\Show;


class CategoryController extends AdminController
{
    /**
     * Title for current resource.
     *
     * @var string
     */
    protected $title = 'Category';

    public function index(Content $content)
    {
        return parent::index($content); // TODO: Change the autogenerated stub
    }

    /**
     * Make a grid builder.
     *
     * @return Grid
     */
    protected function grid()
    {
        $categories = (new Category());
        $grid = new Grid($categories);

        $grid->column('id', __('Id'))->sortable();
        $grid->column('title_vi', __('Title vi'));
        $grid->column('thumbnail', __('Thumbnail'))->image('', 100, 100);
        $grid->column('parent.title_vi', __('Parent'))->label('info');
        $grid->column('is_active', __('Is active'))->switch();
        $grid->column('created_at', __('Created at'))->display(function () {
            return $this->created_at->format('Y-m-d');
        });


        return $grid;
    }

    /**
     * Make a show builder.
     *
     * @param mixed $id
     * @return Show
     */
    protected function detail($id)
    {
        $show = new Show(Category::findOrFail($id));

        $show->field('id', __('Id'));
        $show->field('title_vi', __('Title vi'));
        $show->field('title_en', __('Title en'));
        $show->field('desc_vi', __('Desc vi'));
        $show->field('desc_en', __('Desc en'));
        $show->field('content_vi', __('Content vi'));
        $show->field('content_en', __('Content en'));
        $show->field('thumbnail', __('Thumbnail'));
        $show->field('parent_id', __('Parent id'));
        $show->field('is_active', __('Is active'));
        $show->field('created_at', __('Created at'));
        $show->field('updated_at', __('Updated at'));

        return $show;
    }

    /**
     * Make a form builder.
     *
     * @return Form
     */
    protected function form()
    {
        $form = new Form(new Category());

        $form->text('title_vi', __('Title vi'))->rules('required');
        $form->text('title_en', __('Title en'))->rules('sometimes');
        $form->textarea('desc_vi', __('Desc vi'))->rules('sometimes');
        $form->textarea('desc_en', __('Desc en'))->rules('sometimes');
        $form->ckeditor('content_vi', __('Content vi'))->rules('sometimes');
        $form->textarea('content_en', __('Content en'))->rules('sometimes');
        $form->image('thumbnail', __('Thumbnail'))->rules('required');
        $form->select('parent_id', __('Parent id'))->options(function ($id) {
            $categories = Category::select([
                'id',
                'title_vi as text'
            ])->where('id', '!=', request()->route()->parameter('category'))->get();
            $result = [];
            foreach ($categories as $category) {
                $result[$category->id] = $category->text;
            }
            return $result;
        })->rules('sometimes');
        $form->switch('is_active', __('Is active'))->rules([
            'required']);

        return $form;
    }
}
